One Elf has the important job of loading all of the rucksacks with supplies for the jungle journey. Unfortunately, that Elf didn't quite follow the packing instructions, and so a few items now need to be rearranged.

Each rucksack has two large compartments. All items of a given type are meant to go into exactly one of the two compartments.
The Elf that did the packing failed to follow this rule for exactly one item type per rucksack.

A given rucksack always has the same number of items in each of its two compartments, so the first half of the characters represent items in the first compartment, while the second half of the characters represent items in the second compartment.


## Part 1
Find the item type that appears in both compartments of each rucksack. What is the sum of the priorities of those item types?


```{r}
library(tidyverse)
data <- read_table('data/day3_input.txt',col_names=c('rucksack'))
#data <- data |> 
 # transform(opponent = c('A'=1,'B'=2,'C'=3)[opponent], response =  c('X'=1,'Y'=2,'Z'=3)[response])
```

 


