```{r}
library(tidyverse)
library(rlang)
```
 

## Import and process data
 

```{r}
raw_data <-  read_lines('data/day7_input.txt')
```

Each line has three possible types:
$ -> A command
<numbers> -> A file size
dir <identifier> -> A subdirectory in a listing

The commands are 
cd /
cd <identifier>
cd ..
ls


```{r}
# Directories are environments (so can be modified) of name, sub_dirs, contents.  
directory <- env(empty_env(), name = 'root', sub_dirs = NULL, 
                 file_sizes = NULL, file_names= NULL)
curr_dir <- directory

list_of_dirs <- env(empty_env(), root = 0)

process_cd  <- \(cd, new_dir){
  new_dir <- trimws(new_dir)
  if(new_dir == '/'){
    return(directory)
  } else if(new_dir == '..'){
    return(env_parent(cd)) # will cause error if cd on root
  } else {
    # As far as i can tell this is never called before ls reveals name
    locate <- sapply(cd$sub_dirs, \(x){x$name == new_dir})
    return(cd$sub_dirs[locate][[1]])
  }
}

gen_dir_name <- \(cd){
  name <- cd$name
  current <- cd
  while(! is_empty(env_parent(current))){
    current <- env_parent(current)
    name <- str_c(current$name,"/",name)
  }
  return(name)
}


add_sub <- \(cd, dir) {
 new_sub_dir <- env(cd, name= dir, sub_dirs = NULL,
                                   file_sizes = NULL, file_names = NULL)
 cd$sub_dirs <- c(cd$sub_dirs, new_sub_dir)
 list_of_dirs[[gen_dir_name(new_sub_dir)]] = 0
 return(cd)
}



add_size <-  \(cd, size){
  dir_name <- gen_dir_name(cd)
  list_of_dirs[[dir_name]] = list_of_dirs[[dir_name]] + size
  if(is_empty(env_parent(cd))){
    return()
  }
  add_size(env_parent(cd), size)
}

add_file <- \(cd, file) {
  file <- str_split(file, " ", simplify= TRUE)
  size <- as.numeric(file[1])
  cd$file_sizes <- c(cd$file_sizes, size)
  cd$file_names <- c(cd$file_names, file[[2]])
  # now add file size recursively
  add_size(cd, size)
  return(cd)
}



## Build data structure and accumulate direcotry sizes


for(line in raw_data){
  if(substr(line,1,4) == '$ cd') {
    curr_dir <- process_cd(curr_dir, substr(line,6,nchar(line)))
  } else if(substr(line,1,4) == '$ ls') {
    # nothing to do 
  } else if(substr(line,1,3) == 'dir') {
    curr_dir <- add_sub(curr_dir, substr(line,5,nchar(line)))
  } else {
    # Must be a file now
    curr_dir <- add_file(curr_dir, line)
  }
}
```

 

## Part 1

Find all of the directories with a total size of at most 100000. What is the sum of the total sizes of those directories?

```{r}
v_of_dirs <- as_vector(as.list(list_of_dirs))
sum(v_of_dirs[v_of_dirs <= 100000])

#> 1749646
```

## Part 2

find smallest directory that will free up 30000000

```{r}
current_free_space = 70000000 - v_of_dirs['root']
min(v_of_dirs[v_of_dirs > (30000000 - current_free_space)])
```

Answer : 1498966